# Development environment configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kiwipay_loan_dev
    username: postgres
    password: root
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    enabled: true
    clean-on-validation-error: true

logging:
  level:
    com.kiwipay: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

# Development CORS settings
kiwipay:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:4200,http://localhost:5173
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    allow-credentials: true 